//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intive_patronage.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Users = new HashSet<Users>();
        }

        [IgnoreDataMember]
        [JsonIgnore]
        public int Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string LocalNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [IgnoreDataMember]
        [JsonIgnore]
        public virtual ICollection<Users> Users { get; set; }

        public override bool Equals(object obj)
        {
            if(!(obj is Address))
            {
                return false;
            }

            Address A = (Address) obj;
             
            return (this.Country == A.Country && this.City == A.City && this.PostCode == A.PostCode && this.HouseNumber == A.HouseNumber && this.LocalNumber == A.LocalNumber);
        }
    }
}
